lmms_eval/api/metrics.py
lmms_eval/api/model.py
lmms_eval/api/samplers.py
lmms_eval/api/task.py
lmms_eval/models/__init__.py
lmms_eval/models/fuyu.py
lmms_eval/models/gpt4v.py
lmms_eval/models/instructblip.py
lmms_eval/models/llava.py
lmms_eval/models/minicpm_v.py
lmms_eval/models/qwen_vl.py
lmms_eval/tasks/cmmmu/utils.py
pyproject.toml

pip package

---

lmms_eval/api/samplers.py
lmms_eval/tasks/mmbench/cc_utils.py
lmms_eval/tasks/mmbench/cn_utils.py
lmms_eval/tasks/mmbench/en_utils.py

Fix mmbench dataset submission format

---

pyproject.toml

update version to 0.1.1

---

lmms_eval/tasks/mathverse/mathverse.yaml
lmms_eval/tasks/mathverse/mathverse_evals.py
lmms_eval/tasks/mathverse/mathverse_testmini.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_text_dominant.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_text_lite.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_text_only.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_vision_dominant.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_vision_intensive.yaml
lmms_eval/tasks/mathverse/mathverse_testmini_vision_only.yaml
lmms_eval/tasks/mathverse/utils.py

Add the evaluation of MathVerse.

Add MathVerse

---

lmms_eval/models/__init__.py
lmms_eval/models/idefics2.py
lmms_eval/tasks/mmmu/mmmu_val.yaml
lmms_eval/tasks/scienceqa/scienceqa_img.yaml

add idefics2

---

lmms_eval/models/__init__.py
lmms_eval/models/qwen_vl_api.py

[Feat] Add qwen vl api

---

pyproject.toml

[Small Update] Update the version of LMMs-Eval

---

lmms_eval/tasks/ii_bench/ii_bench.yaml
lmms_eval/tasks/ii_bench/utils.py

---
I have updated [II-Bench](https://ii-bench.github.io/) in your repository, setting it to the "none" configuration as per the paper. Testing with idefics2-8b shows results that are largely consistent with those in the paper (test: 68.12%, paper: 67.69%). The dataset has not yet been uploaded to lmms-lab, so please fork the dataset from https://huggingface.co/datasets/m-a-p/II-Bench.

add II-Bench

---

lmms_eval/models/phi3v.py
lmms_eval/tasks/qbench/abench_dev.yaml
lmms_eval/tasks/qbench/qbench2_dev.yaml
lmms_eval/tasks/qbench/qbench_dev.yaml
lmms_eval/tasks/qbench/qbenchs_dev.yaml
lmms_eval/tasks/qbench/utils.py

Support Q-Bench, Q-Bench2, A-Bench.
It is now working on Phi3v, Idefics2 smoothly, the result is aligned.
We also revise the logic of image placeholders in Phi3V, so that it can support multiple images.

Q-Bench, Q-Bench2, A-Bench

---

README.md
docs/README.md
tools/make_image_hf_dataset.ipynb
tools/make_video_hf_dataset.ipynb

Add docs for datasets upload to HF

---

lmms_eval/tasks/vitatecs/_default_template_yaml
lmms_eval/tasks/vitatecs/_vitatecs.yaml
lmms_eval/tasks/vitatecs/utils.py
lmms_eval/tasks/vitatecs/vitatecs_compositionality.yaml
lmms_eval/tasks/vitatecs/vitatecs_direction.yaml
lmms_eval/tasks/vitatecs/vitatecs_intensity.yaml
lmms_eval/tasks/vitatecs/vitatecs_localization.yaml
lmms_eval/tasks/vitatecs/vitatecs_sequence.yaml
lmms_eval/tasks/vitatecs/vitatecs_type.yaml

This PR adds VITATECS as a caption matching task, aimed at evaluating the temporal understanding of video LLMs from six aspects. 
links: [arXiv](https://arxiv.org/abs/2311.17404), [Github](https://github.com/lscpku/VITATECS), [huggingface](https://huggingface.co/datasets/lscpku/VITATECS)
Video-LLaVA
```bash
python3 -m accelerate.commands.launch \
--num_processes=8 \
-m lmms_eval \
--model video_llava \
--model_args pretrained="LanguageBind/Video-LLaVA-7B-hf" \
--tasks vitatecs \
--batch_size 1 \
--log_samples_suffix video_llava \
--output_path ./logs/
```
Results
```
|           Tasks            |Version|Filter|n-shot| Metric | Value |   |Stderr|
|----------------------------|-------|------|-----:|--------|------:|---|------|
|vitatecs                    |N/A    |none  | …
```

Add task VITATECS

---

lmms_eval/evaluator.py
lmms_eval/tasks/wild_vision_bench/_default_template_yaml
lmms_eval/tasks/wild_vision_bench/utils.py
lmms_eval/tasks/wild_vision_bench/wild_vision_bench0617.yaml

---
Wild vision bench from https://huggingface.co/datasets/WildVision/wildvision-arena-data
Because the scoring logic is based on ranking 
- Worse
- Worse++
- Tie
- Better
- Better++
I choose to set the score for each question to be 
- "-1" for Worse
- "-2" for Worse++
- "0" for Tie
- "1" for Better
- "2" for Better++
The scores are added and take mean for each question to output a final aggregated score

Add wild vision bench

---

lmms_eval/tasks/detailcaps/_default_template_detailcaps_yaml
lmms_eval/tasks/detailcaps/detailcaps.yaml
lmms_eval/tasks/detailcaps/utils.py
pyproject.toml

Adding detail image caption evaluation with DetailCaps-4870 benchmark and CAPTURE metric proposed in [Benchmarking and Improving Detail Image Caption](https://arxiv.org/abs/2405.19092).
Dataset: https://huggingface.co/datasets/foundation-multimodal-models/DetailCaps-4870
Code: https://github.com/foundation-multimodal-models/CAPTURE

Add detailcaps

---

lmms_eval/tasks/muirbench/muirbench.yaml
lmms_eval/tasks/muirbench/utils.py

Add muirbench

---

lmms_eval/tasks/mirb/mirb.yaml
lmms_eval/tasks/mirb/utils.py

----
Add a new benchmark **MIRB**, for multi-image evaluation.
Paper: https://arxiv.org/abs/2406.12742v1
Original code: https://github.com/ys-zong/MIRB
HF: https://huggingface.co/datasets/VLLMs/MIRB-hf
Example evaluation result:

Add a new benchmark: MIRB

---

lmms_eval/models/llava_vid.py

- Add default values for mm_resampler_location and mm_newline_position to make sure Llavavid model can run successfully.

Add default values for mm_resampler_location and mm_newline_position to make sure Llavavid model can run successfully.

---

docs/current_tasks.md
lmms_eval/tasks/mmstar/mmstar.yaml
lmms_eval/tasks/mmstar/utils.py

Implemented [MMStar](https://github.com/MMStar-Benchmark/MMStar).

Add MMStar

---

lmms_eval/tasks/seedbench/utils.py

Fix utils.py
builtin method lower()

Fix utils.py

---

lmms_eval/evaluator.py

Fix a small typo for live_bench

---

README.md

Update the blog link

---

lmms_eval/api/task.py
lmms_eval/tasks/refcoco+/_default_template_bbox_rec_yaml
lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_testA.yaml
lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_testB.yaml
lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_val.yaml
lmms_eval/tasks/refcoco+/utils_rec.py
lmms_eval/tasks/refcoco/_default_template_bbox_rec_yaml
lmms_eval/tasks/refcoco/refcoco_bbox_rec_test.yaml
lmms_eval/tasks/refcoco/refcoco_bbox_rec_testA.yaml
lmms_eval/tasks/refcoco/refcoco_bbox_rec_testB.yaml
lmms_eval/tasks/refcoco/refcoco_bbox_rec_val.yaml
lmms_eval/tasks/refcoco/utils_rec.py
lmms_eval/tasks/refcocog/_default_template_bbox_rec_yaml
lmms_eval/tasks/refcocog/refcocog_bbox_rec_test.yaml
lmms_eval/tasks/refcocog/refcocog_bbox_rec_val.yaml
lmms_eval/tasks/refcocog/utils_rec.py

This is the PR for cherry picking to bring back the PR #52. Have no idea why it disappeared in the repo. Probably it was been deleted from the merging in one release.

Bring back PR#52

---

lmms_eval/models/srt_api.py

[Minor] Add kill sglang process

---

lmms_eval/evaluator.py
lmms_eval/tasks/mmmu_pro/mmmu_pro.yaml

Remove unnecessary LM object removal in evaluator

---

lmms_eval/models/video_llava.py

This PR fix a minor error in video llava. Replace max_length with max_new_tokens

[Minor] Fix max_new_tokens in video llava

---

pyproject.toml

This PR updates the version requirement for `transformers`.

Update the version requirement for `transformers`

---

lmms_eval/models/cambrian.py
lmms_eval/tasks/wild_vision_bench/utils.py

1. fix wildvision raw score calculation
2. add cambrian model

Refactor wild_vision_aggregation_raw_scores to calculate average score

---

lmms_eval/evaluator.py

[Fix] Bring back process result pbar

---

.gitignore
lmms_eval/api/task.py
lmms_eval/caching/cache.py
lmms_eval/evaluator.py
lmms_eval/tasks/wild_vision_bench/utils.py

This pull request includes the following changes:
- Refactor the caching module for the LM evaluation harness.
- Fix an issue with serializing non-serializable objects in the caching module.
- Add error logging and a retry mechanism in the `get_chat_response` function.

Refactor caching module and fix serialization issue

---

lmms_eval/api/task.py

This fix the issue when metadata is a list

[Minor] Bring back fix for metadata

---

check_missing.py
check_reverse.py
lmms_eval/api/samplers.py
lmms_eval/models/gpt4v.py
lmms_eval/models/model_utils/load_video.py
lmms_eval/tasks/mmmu/utils.py
lmms_eval/tasks/mmmu_for_testing/utils.py
lmms_eval/tasks/videosearch/utils.py

If `fps=None`, there is no limitation for `fps`.

[Feat] add `fps` parameter for `GPT4V`

---

lmms_eval/tasks/mmworld/mmworld.yaml
lmms_eval/tasks/mmworld/utils.py

> Before you open a pull-request, please check if a similar issue already exists or has been closed before.
> 
> ### When you open a pull-request, please be sure to include the following
> 
> - [x] A descriptive title: [xxx] XXXX
> - [x] A detailed description
> 
> Thank you for your contributions!
> 
Hi authors,
Thanks for your awesome work for creating such a useful tools!
This pull-request add a new task MMWorld https://mmworld-bench.github.io/, a new benchmark for multi-discipline, multi-faceted multimodal video understanding.

Support new task mmworld

---

docs/current_tasks.md

- Add text-tasks
- Add MMT and MMT-MI
- Add links to tasks' homepage

Update current tasks.md

---

pyproject.toml

Bump version to 0.2.4 and remove unused dependencies

---

lmms_eval/tasks/clotho_aqa/_default_template_yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_test.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_test_all.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_test_majority.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_test_unanimous.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_val.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_val_all.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_val_majority.yaml
lmms_eval/tasks/clotho_aqa/clotho_aqa_val_unanimous.yaml
lmms_eval/tasks/clotho_aqa/clotho_asqa_test_v2.yaml
lmms_eval/tasks/clotho_aqa/utils.py

Audio bench: https://github.com/AudioLLMs/AudioBench
Difference from the original task:
- Different answer format from the original clotho_aqa: freeform answer instead of single word.
- Use LLM for scoring (from 1-5 score) instead of exact-matching

[Feat] add audiobench version of clothoaqa

---

tools/live_bench/live_bench/data_generator/live_bench_data.py

[Fix] A small fix for the `LiveBench` checker

---

lmms_eval/models/qwen_vl_api.py

[Fix] Fix extra calling in qwen_vl_api, use tempfile for tmp

---

lmms_eval/tasks/common_voice_15/common_voice_15.yaml
lmms_eval/tasks/common_voice_15/common_voice_15_en.yaml
lmms_eval/tasks/common_voice_15/common_voice_15_fr.yaml
lmms_eval/tasks/common_voice_15/common_voice_15_zh-CN.yaml
lmms_eval/tasks/common_voice_15/utils.py
lmms_eval/tasks/librispeech/librispeech_dev_clean.yaml
lmms_eval/tasks/librispeech/librispeech_dev_other.yaml
lmms_eval/tasks/librispeech/librispeech_test_clean.yaml
lmms_eval/tasks/librispeech/librispeech_test_other.yaml
lmms_eval/tasks/people_speech/people_speech_val.yaml
lmms_eval/tasks/people_speech/utils.py

add common_voice_15 and people_speech tasks

add common_voice_15 and people_speech tasks

---

lmms_eval/models/llava_vid.py

Update video_decode_backend to "decord"

---

lmms_eval/models/model_utils/audio_processing.py
lmms_eval/models/qwen2_audio.py
lmms_eval/tasks/air_bench/utils.py
lmms_eval/tasks/clotho_aqa/utils.py
lmms_eval/tasks/common_voice_15/utils.py
lmms_eval/tasks/gigaspeech/utils.py
lmms_eval/tasks/librispeech/utils.py
lmms_eval/tasks/openhermes/utils.py
lmms_eval/tasks/people_speech/utils.py

[Refactor] Fixing doc to audio return type, qwen_audio revise

---

lmms_eval/tasks/muchomusic/muchomusic.yaml
lmms_eval/tasks/muchomusic/utils.py
lmms_eval/tasks/vocalsound/_default_template_yaml
lmms_eval/tasks/vocalsound/utils.py
lmms_eval/tasks/vocalsound/vocalsound_test.yaml
lmms_eval/tasks/vocalsound/vocalsound_val.yaml

- doc_to_audio return library instead of array

Add muchomusic and vocalsound task

---

lmms_eval/tasks/alpaca_audio/alpaca_audio.yaml
lmms_eval/tasks/alpaca_audio/utils.py
lmms_eval/tasks/gigaspeech/gigaspeech.yaml
lmms_eval/tasks/gigaspeech/gigaspeech_xl_dev.yaml
lmms_eval/tasks/gigaspeech/gigaspeech_xl_test.yaml
lmms_eval/tasks/gigaspeech/utils.py

- added config yaml for `xl_dev` and `xl_test`
- fixed error subset `l` config; opportunistically removed some used code
- `xl_test` has intermittent issue, possibly due to OOM

[feat] added gigaspeech config

---

lmms_eval/tasks/videoperception/utils.py
lmms_eval/tasks/videoperception/video_mmmu.yaml
lmms_eval/tasks/videosearch/utils.py
tools/get_video_avg_time_videoperception.py

Add video_mmmu task configuration

---

lmms_eval/tasks/tedlium/tedlium_dev_test.yaml
lmms_eval/tasks/tedlium/tedlium_long_form.yaml
lmms_eval/tasks/tedlium/utils.py

add tedlium_long_form and tedlium_dev_test tasks

add tedlium_long_form and tedlium_dev_test tasks

---

lmms_eval/models/model_utils/load_video.py
lmms_eval/models/qwen2_vl.py

```sh
```
Feature request from #336

[Update] Allow pass in max pixels and num frames in qwen2vl

---

lmms_eval/tasks/wavcaps/utils.py
lmms_eval/tasks/wavcaps/wavcaps.yaml

- added support on WavCaps using `AudioLLMs/wavcaps_test` dataset.

[Feat] add-wavcaps

---

docs/current_tasks.md
docs/run_examples.md
lmms_eval/models/__init__.py
lmms_eval/models/auroracap.py
lmms_eval/models/llava_onevision_moviechat.py
lmms_eval/models/moviechat.py

[Feat] Add AuroraCap, MovieChat, LLaVA-OneVision-MovieChat

---

lmms_eval/evaluator.py
lmms_eval/evaluator_utils.py
lmms_eval/models/qwen2_audio.py
lmms_eval/tasks/librispeech/librispeech_dev_clean.yaml
lmms_eval/tasks/librispeech/librispeech_dev_other.yaml
lmms_eval/tasks/librispeech/librispeech_test_clean.yaml
lmms_eval/tasks/librispeech/librispeech_test_other.yaml
pyproject.toml

Update dep and fix log samples for audio

---

lmms_eval/tasks/vocalsound/vocalsound_val.yaml

change the aggregation function for vocalsound_val

fix vocalsound

---

lmms_eval/models/qwen2_audio.py

[Fix] Qwen prompt for alignment

---

lmms_eval/models/longva.py
lmms_eval/models/model_utils/load_video.py
lmms_eval/models/qwen2_vl.py
lmms_eval/models/vila.py

Add longva fps mode, Rewrite Qwen video extraction, Add VILA FPS mode

---

lmms_eval/tasks/air_bench/air_bench_chat_mixed.yaml
lmms_eval/tasks/air_bench/air_bench_chat_music.yaml
lmms_eval/tasks/air_bench/air_bench_chat_sound.yaml
lmms_eval/tasks/air_bench/air_bench_chat_speech.yaml
lmms_eval/tasks/air_bench/air_bench_foundation_music.yaml
lmms_eval/tasks/air_bench/air_bench_foundation_sound.yaml
lmms_eval/tasks/air_bench/air_bench_foundation_speech.yaml
lmms_eval/tasks/air_bench/utils.py
lmms_eval/tasks/alpaca_audio/utils.py
lmms_eval/tasks/clotho_aqa/utils.py
lmms_eval/tasks/openhermes/utils.py

- Issue: Too Many Requests errors in API calls; so I added retry for each call
- Improve air_bench_foundation aggregation to return result for each tasks rather than the total average

Add retry for gpt api call and improve air_bench aggregation function

---

lmms_eval/models/model_utils/load_video.py
lmms_eval/models/qwen2_vl.py

[Feat] add resize image in video extraction

---

lmms_eval/api/task.py
lmms_eval/models/llava_hf.py
lmms_eval/models/qwen2_vl.py

```sh
```
This PR is a fix patch that fix multiple issues #388 #370 #363

[Fix] Qwen2_VL, anls agg, mc output type

---

lmms_eval/tasks/hallusion_bench/evaluate_hb.py

[Fix] Fix hallu bench

---

lmms_eval/models/claude.py
lmms_eval/models/internvl2.py

Fix:
1. Shard error in InternVL2 model
2. Wrong response saved when claude output an error

[Fix] fix some bugs in InternVL2 and Claude

---

lmms_eval/models/idefics2.py

Add video processing logic for idefics2

---

pyproject.toml

https://pypi.org/project/lmms-eval/0.3.0/

PyPI 0.3.0

---

lmms_eval/tasks/mix_evals/README.md
lmms_eval/tasks/mix_evals/audio2text/mix_evals_audio2text_hard.yaml

MixEval-X Readme

---

lmms_eval/models/llama_vision.py

https://github.com/EvolvingLMMs-Lab/lmms-eval/pull/434#discussion_r1874177714

Fix Llama vision mentioned in #434

---

lmms_eval/tasks/naturalbench/naturalbench.yaml
lmms_eval/tasks/naturalbench/utils.py

[Fixed] metric names in NaturalBench dataset

[Fixed] metric names in NaturalBench dataset

---

lmms_eval/tasks/mmvetv2/mmvetv2.yaml
lmms_eval/tasks/mmvetv2/mmvetv2_group_img.yaml
lmms_eval/tasks/mmvetv2/utils.py

Fix MMVet V2

---

lmms_eval/tasks/__init__.py

[Fix] remove useless print statements

---

lmms_eval/models/internvl2.py

…um_segments usage in InternVL2 class
```sh
```

fix internvl2 numframe

---

lmms_eval/models/llava_onevision.py

[Fix] use isinstance for type checking of visual input

---

docs/current_tasks.md
lmms_eval/tasks/illusionvqa/illusionvqa.yaml
lmms_eval/tasks/illusionvqa/illusionvqa_comprehension.yaml
lmms_eval/tasks/illusionvqa/illusionvqa_soft_localization.yaml
lmms_eval/tasks/illusionvqa/utils.py

Added new task - [IllusionVQA-A Challenging Optical Illusion Dataset for Vision Language Models](https://illusionvqa.github.io/)
(I am an author of the paper)
Added code for 0-shot and few-shot evaluation.
Tested with gpt4o and 0-shots results match our scripts.
Is multimodal fewshot functional?

Added new task IllusionVQA (COLM2024)

---

lmms_eval/models/llava_onevision.py

[Small Update] Update llavaonevision default value

---

lmms_eval/models/oryx.py
lmms_eval/models/vila.py

Oryx & Vila

---

lmms_eval/__main__.py
lmms_eval/api/task.py
lmms_eval/evaluator.py

```sh
```
This PR made the following revision:
1. Optimize the build requests for all the dataset and use an iterator to avoid out of memory and speed
2. Remove audio from the build request and postprocess dataset for speed performance
3. Add a process with media args to allow if you want to have media in your postprocess process

[Optimization] Optimize build requests, postprocess

---

lmms_eval/api/task.py

[Fix] Use no media iterator

---

lmms_eval/models/llama_vision.py

fix adding bos twice and remove eos in decoded results

Fix llama_vision chat_template and decode

---

lmms_eval/models/internvl2.py
lmms_eval/models/qwen2_audio.py

Fix two wrong device_map usage

Fix device_map

---

lmms_eval/tasks/covost2_zh_en/_default_template_yaml
lmms_eval/tasks/covost2_zh_en/covost2_zh_en.yaml
lmms_eval/tasks/covost2_zh_en/covost2_zh_en_dev.yaml
lmms_eval/tasks/covost2_zh_en/covost2_zh_en_test.yaml
lmms_eval/tasks/covost2_zh_en/utils.py

covost 2 zh en
- covost 2 zh en test
- covost 2 zh en dev

Add covost2 zh en

---

lmms_eval/tasks/common_voice_15/_default_template_yaml
lmms_eval/tasks/common_voice_15/common_voice_15_en.yaml
lmms_eval/tasks/common_voice_15/common_voice_15_fr.yaml
lmms_eval/tasks/common_voice_15/common_voice_15_zh-CN.yaml
lmms_eval/tasks/common_voice_15/utils.py
lmms_eval/tasks/gigaspeech/utils.py

[Fix] Fix dataset processing logic for common voice and gigaspeech

---

lmms_eval/tasks/common_voice_15/utils.py

Fix language in common voice

---

lmms_eval/tasks/fleurs/_default_template_yaml

Change fleurs path

---

lmms_eval/tasks/mmmu/utils.py

Fix mmmu doc to text

---

.github/workflows/lint.yml
lmms_eval/models/__init__.py
lmms_eval/models/ola.py

Merging Ola

---

lmms_eval/tasks/mlvu/utils.py

modify utils.py

---

lmms_eval/tasks/ocrbench_v2/IoUscore_metric.py
lmms_eval/tasks/ocrbench_v2/TEDS_metric.py
lmms_eval/tasks/ocrbench_v2/ocrbench_v2.yaml
lmms_eval/tasks/ocrbench_v2/page_ocr_metric.py
lmms_eval/tasks/ocrbench_v2/parallel.py
lmms_eval/tasks/ocrbench_v2/spotting_eval/readme.txt
lmms_eval/tasks/ocrbench_v2/spotting_eval/rrc_evaluation_funcs_1_1.py
lmms_eval/tasks/ocrbench_v2/spotting_eval/script.py
lmms_eval/tasks/ocrbench_v2/spotting_metric.py
lmms_eval/tasks/ocrbench_v2/upload_ocrbench_v2.py
lmms_eval/tasks/ocrbench_v2/utils.py
lmms_eval/tasks/ocrbench_v2/vqa_metric.py

add OCRBench v2

---

lmms_eval/models/__init__.py
lmms_eval/models/internvideo2_5.py
lmms_eval/models/videochat_flash.py

Welcome to merge our new SoTA Video MLLM: [VideoChat-Flash](https://github.com/OpenGVLab/VideoChat-Flash) and [InternVideo2.5](https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo2.5).

Add VideoChat-Flash and InternVideo2.5

---

lmms_eval/models/__init__.py
lmms_eval/models/videollama3.py

This PR introduces support for [VideoLLaMA3](https://github.com/DAMO-NLP-SG/VideoLLaMA3),  a frontier multimodal foundation model for video understanding.
Below is a screenshot of the evaluation result on videomme:

[Feat] Support VideoLLaMA3

---

lmms_eval/tasks/worldsense/utils.py
lmms_eval/tasks/worldsense/worldsense.yaml
lmms_eval/tasks/worldsense/worldsense_w_subtitle.yaml

Add WorldSense

---

lmms_eval/models/__init__.py
lmms_eval/models/phi4_multimodal.py

[Feat] Add Phi-4 multimodal

---

lmms_eval/tasks/mme_cot/mme_cot_direct.yaml
lmms_eval/tasks/mme_cot/mme_cot_reason.yaml
lmms_eval/tasks/mme_cot/utils.py

1. adding mme-cot, currently support run the inference procedure and generate submission files. 
We need:
1. A README file to introduce how to use MME-COT's repo code to finish evaluation. @CaraJ7 
```sh
```

[Task] adding MME-COT

---

lmms_eval/tasks/open_asr/_default_template_yaml
lmms_eval/tasks/open_asr/openasr.yaml
lmms_eval/tasks/open_asr/openasr_ami.yaml
lmms_eval/tasks/open_asr/openasr_common_voice.yaml
lmms_eval/tasks/open_asr/openasr_earnings22.yaml
lmms_eval/tasks/open_asr/openasr_gigaspeech.yaml
lmms_eval/tasks/open_asr/openasr_librispeech.yaml
lmms_eval/tasks/open_asr/openasr_librispeech_test_clean.yaml
lmms_eval/tasks/open_asr/openasr_librispeech_test_other.yaml
lmms_eval/tasks/open_asr/openasr_spgispeech.yaml
lmms_eval/tasks/open_asr/openasr_voxpopuli.yaml
lmms_eval/tasks/open_asr/utils.py

[Feat] Add openasr

---

.gitignore
lmms_eval/tasks/k12/k12.yaml
lmms_eval/tasks/k12/utils.py
lmms_eval/tasks/mathverse/mathverse_testmini.yaml
lmms_eval/tasks/mathvision/mathvision_reason_test.yaml
lmms_eval/tasks/mathvision/mathvision_reason_testmini.yaml
lmms_eval/tasks/mathvision/utils.py
lmms_eval/tasks/mathvista/mathvista_evals.py
lmms_eval/tasks/mathvista/mathvista_testmini_cot.yaml
lmms_eval/tasks/mathvista/utils.py
lmms_eval/tasks/mme_cot/mme_cot_reason.yaml
lmms_eval/tasks/mmmu/mmmu_val_thinking.yaml
lmms_eval/tasks/mmmu/utils.py
lmms_eval/tasks/olympiadbench/en_utils.py
lmms_eval/tasks/olympiadbench/olympiadbench_testmini.yaml
lmms_eval/tasks/olympiadbench/testmini_utils.py

* Add K12 task configuration and utility functions for visual reasoning.
* Introduce OlympiadBench task configuration and utility functions for evaluation.
* Update existing tasks with new generation parameters and visual reasoning tags.
* Remove obsolete MMMU validation reasoning task.
```sh
```

[Tasks] New tasks for Visual Reasoning Collection

---

lmms_eval/tasks/mme_cot/mme_cot_reason.yaml
lmms_eval/tasks/mme_cot/utils.py

[Feat] fix MME COT, add llm as judge eval

---

lmms_eval/models/model_utils/audio_processing.py
lmms_eval/models/qwen2_audio.py
lmms_eval/tasks/librispeech/_default_yaml_template
lmms_eval/tasks/librispeech/librispeech_long.yaml
lmms_eval/tasks/librispeech/librispeech_test_clean_long.yaml
lmms_eval/tasks/librispeech/librispeech_test_other_long.yaml
lmms_eval/tasks/librispeech/utils.py

[Feat] Adding libri long

---

lmms_eval/models/openai_compatible.py

The original script doesn't support the newer version of openai api.

Modify the openai api to support o1 and o3

---

lmms_eval/models/qwen2_5_vl.py
lmms_eval/models/qwen2_vl.py
lmms_eval/tasks/VisualPuzzles/utils.py

- Added `system_prompt`, `interleave_visuals`, and `max_length` parameters to Qwen2_VL class.
- Simplified device assignment logic for single process scenarios.
- Improved visual processing by refining how visuals are handled and ensuring proper mapping to contexts.
- Enhanced message construction to support interleaving of visuals and text based on placeholders.
- Set default generation parameters and refined handling of generated outputs to ensure proper trimming and formatting.
```sh
```

[Feat] Enhance Qwen model with additional parameters and improved visual handling

---

lmms_eval/models/qwen2_5_omni.py
lmms_eval/tasks/vsibench/utils.py

[Fix] Better Qwen omni and linting

---

lmms_eval/models/qwen2_5_vl.py
lmms_eval/models/vllm.py
lmms_eval/tasks/capability/prompt.py
lmms_eval/tasks/capability/utils.py
lmms_eval/tasks/llava-in-the-wild/llava-in-the-wild_ko.yaml
lmms_eval/tasks/mathvision/utils.py

Modify the GPT evaluation model in K-LLaVA-W from "gpt-4-0613" to "gpt-4o-2024-08-06".
The GPT evaluation model used to measure this benchmark can be found in https://arxiv.org/pdf/2411.19103 (Page 5).

[fix] modify the GPT evaluation model

---

lmms_eval/tasks/xlrs/XLRS-lite.yaml
lmms_eval/tasks/xlrs/mcq_utils.py

Hi,
This PR adds a new benchmark, [XLRS-Bench](https://github.com/AI9Stars/XLRS-Bench), a comprehensive benchmark for evaluating the perception and reasoning capabilities of MLLMs in ultra-high-resolution RS scenarios, featuring the largest average image size of 8,500 × 8,500 observed thus far. 
XLRS-Bench-lite is subset of XLRS-Bench, containing about 3k QA pairs.
For evaluation:
```bash
accelerate launch --num_processes 8 --main_process_port 12345 -m lmms_eval \
--model "qwen2_5_vl" \
--model_args "pretrained=Qwen/Qwen2.5-VL-7B-Instruct,use_flash_attention_2=True"  \
--tasks xlrs-lite \
--batch_size 1 \
--log_samples_suffix qwen2_5_vl_xlrs_lite \
--output_path ./logs/
```

[Task] Add new task: XLRS-Bench-lite

---

lmms_eval/models/aero.py
lmms_eval/models/llava_hf.py
lmms_eval/tasks/coco_cap/coco_karpathy_test.yaml
lmms_eval/tasks/coco_cap/coco_karpathy_val.yaml
pyproject.toml

[Fix] Minor fix on some warning messages

---

lmms_eval/tasks/mmsi_bench/msr_bench.yaml
lmms_eval/tasks/mmsi_bench/utils.py

add mmsi-bench (https://arxiv.org/abs/2505.23764)

add mmsi-bench (https://arxiv.org/abs/2505.23764)

---

lmms_eval/evaluator.py
lmms_eval/tasks/videomathqa/cot_postprocess.py
lmms_eval/tasks/videomathqa/cot_step_evaluation.py
lmms_eval/tasks/videomathqa/utils.py

It is necessary to add a `WORLD_SIZE > 1` check in the `evaluate` function to ensure it works correctly when not using multiple GPUs.

[fix] ensure synchronization not be used without distributed execution

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml

Add claude GitHub actions 1752118403023

---

lmms_eval/models/chat/qwen2_5_vl.py
lmms_eval/models/chat/sglang.py
lmms_eval/models/chat/vllm.py
lmms_eval/protocol.py

fix: Fix video loading logic and add protocol for loading

---

lmms_eval/tasks/csbench/csbench.yaml
lmms_eval/tasks/csbench/csbench_assertion.yaml
lmms_eval/tasks/csbench/csbench_mcq.yaml
lmms_eval/tasks/csbench/utils.py

add csbench
