EvolvingLMMs-Lab/lmms-eval

README.md, lmms_eval/__main__.py, lmms_eval/models/llava.py, lmms_eval/tasks/llava-in-the-wild/llava-in-the-wild.yaml, pyproject.toml
1. Update correct usage for running 34B model using GPUs with constrained memory.
```python
lmms_eval --model=llava \
--model_args=pretrained=liuhaotian/llava-v1.6-34b,conv_template=mistral_direct,device_map=auto \
--tasks=mme,mmmu_val \
--batch_size=1 \
--log_samples_suffix=tp_evals \
--output_path="./logs/" \
--wandb_args=project=lmms-eval,job_type=eval,entity=libo0013
```
2. Update the gpt-4 version to `gpt-4-0613` for llava-w's evaluation. `gpt-4-0314` API has been deprecated.
=> [Feat] add correct tensor parallelism for larger size model.

lmms_eval/tasks/mmbench/cc_utils.py, lmms_eval/tasks/mmbench/cn_utils.py, lmms_eval/tasks/mmbench/en_utils.py, lmms_eval/tasks/mmbench/mmbench.yaml, lmms_eval/tasks/mmbench/mmbench_cc.yaml, lmms_eval/tasks/mmbench/mmbench_cn.yaml, lmms_eval/tasks/mmbench/mmbench_cn_dev.yaml, lmms_eval/tasks/mmbench/mmbench_en.yaml, lmms_eval/tasks/mmbench/mmbench_en_dev.yaml, lmms_eval/tasks/mmbench/mmbench_evals.py
=> [WIP] adding mmbench dev evaluation (#75)

lmms_eval/models/llava_hf.py
A small fix to allow users to disable options like FA2 in the command line (previously `None` was cast to `str`)
=> Fix types to allow nullables in `llava_hf.py`

README.md, lmms_eval/api/task.py, lmms_eval/tasks/refcoco+/_default_template_bbox_rec_yaml, lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_testA.yaml, lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_testB.yaml, lmms_eval/tasks/refcoco+/refcoco+_bbox_rec_val.yaml, lmms_eval/tasks/refcoco+/utils_rec.py, lmms_eval/tasks/refcoco/_default_template_bbox_rec_yaml, lmms_eval/tasks/refcoco/refcoco_bbox_rec_test.yaml, lmms_eval/tasks/refcoco/refcoco_bbox_rec_testA.yaml, lmms_eval/tasks/refcoco/refcoco_bbox_rec_testB.yaml, lmms_eval/tasks/refcoco/refcoco_bbox_rec_val.yaml, lmms_eval/tasks/refcoco/utils_rec.py, lmms_eval/tasks/refcocog/_default_template_bbox_rec_yaml, lmms_eval/tasks/refcocog/refcocog_bbox_rec_test.yaml, lmms_eval/tasks/refcocog/refcocog_bbox_rec_val.yaml, lmms_eval/tasks/refcocog/utils_rec.py
This PR adds REC evaluations, assuming that bounding boxes will be output as raw square brackets and coordinates. It adds REC eval for all RefCOCO sets (RefCOCO, RefCOCO+, RefCOCOg). Specifically: 
- `.yaml` files are added, both for the defaults and specifics for splits 
- `util_rec.py` for each set (identical across RefCOCO sets) 
- minor modifications to Task to change how no_image_dataset is created. I've tried to do this more efficiently so that we can explode the dataset into one answer-bounding box pair instead of a set of answers for a single bounding box.
=> Add REC tasks for testing model ability to locally ground objects, given a description. This adds REC for all RefCOCO datasets.

lmms_eval/models/__init__.py, lmms_eval/models/llava_sglang.py
Add llava_sglang.
Some caveats:
1. sglang currently only supports single-image input. We use the first image by default.
2. there is no concept of batch size in sglang. We use "parallel" instead.
3. use python -m instead of accelerate
4. sglang only supports tensor parallel (tp_size). It does not support data parallel
example eval config and script: 
```yaml
- model: llava_sglang
model_args: pretrained=liuhaotian/llava-v1.6-34b,tokenizer=liuhaotian/llava-v1.6-34b-tokenizer,conv_template=chatml,tp_size=8,parallel=4
tasks: mme
batch_size: 1
log_samples: true
log_samples_suffix: eval_mme 
output_path: "./logs/"
```
```bash
python -m lmms_eval --config config.yaml
=> add Llava-SGlang

lmms_eval/models/qwen_vl.py
Hi! This PR fixes an issue in the Qwen-VL `generate_until` method that was caused by a typo (`contexts[i]` was being referenced as `context[i]`; singular). I also added an `if` statement that converts `contexts` to a list so we can use _item assignment_ with the indexing operator. Finally, made a minor refactor to make the construction of the `query` more readable.
=> Fix typo in Qwen-VL that was causing "reference before assignment"

lmms_eval/tasks/websrc/utils.py
Apologies for another rapid PR on this; I was doing additional validation with this benchmark yesterday and realized the F1-scores were incorrectly computed. Instead of being token-level F1, WebSRC was scoring based on a character-level. 
This PR is a small bugfix that rectifies that (and a KeyError in submission compilation). 
Unfortunately, the previous metrics gave an elevated sense of how LLaVA performs. The token-level F1 shows a score of 30.9 now with the following cross-tabs: 
| Model | auto | book | camera | game | jobs | movie | phone | restaurant | sports | university | hotel |
|-------|------|------|--------|------|------|-------|-------|-----------|-------|-----------|-------|
| [liuhaotian/llava-v1.5-7b](https://huggingface.co/liuhaotian/llava-v1.5-7b) | 48.0 | 60.7 | - | …
=> Bugfix: WebSRC should be token-level F1 NOT character-level

miscs/repr_scripts.sh
When reproduce the llava model evaluation, some errors may occur like this issue:
+ https://github.com/EvolvingLMMs-Lab/lmms-eval/issues/33
This is because we don't pass the `device_map` according to the repr script here:
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/9dfb53afb49adb6d20607bc3ca989591969f5432/miscs/repr_scripts.sh#L14
which leads to the error in llava model code:
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/9dfb53afb49adb6d20607bc3ca989591969f5432/lmms_eval/models/llava.py#L68-L73
It seems that when `num_processes` is >1, it run into the `if` branch to select a specific cuda device, `cuda:0` for example.
and if the `num_processes` is 1 (that's how we do according to the reproduce script), it need user to define a device_map strategy, `auto` for example. And if we …
=> [Fix] repr llava doc

lmms_eval/models/__init__.py, lmms_eval/models/phi3v.py, lmms_eval/tasks/mathvista/mathvista_testmini.yaml
Description:
1. Adding the newly announced Phi-3 Vision model into the benchmark.
2. Model reproduces reported numbers:
| Evaluation | MMMU | ScienceQA-Img | MathVista | ChartQA | AI2D | TextVQA | POPE | MMB |
| -------- | ------- | --- | ---| --- | --- | --- | --- | --- |
| LMMs-Eval  | 40.7  |  90.6 | 44.4 | 81.4 | 77.1 | 69.4 | 86.2 | gpt=73.7 / plain_accuracy=80.5|
| Reported | 40.4 |  90.8 | 44.5 | 81.4 | 76.7 | 70.9 | 85.8 | plain_accuracy=80.5| 
For the results shown above, we used 4 RTX A600 GPUs.
=> Adding microsoft/Phi-3-vision-128k-instruct model.

lmms_eval/tasks/conbench/conbench.yaml, lmms_eval/tasks/conbench/utils.py
This PR adds ConBench as an additional benchmark about **Consistency**.
When faced with prompts in different sizes of solution spaces, Large vision-language models (LVLMs) fail to always give consistent answers regarding the same knowledge point. This inconsistency of answers between different solution spaces is prevalent in LVLMs and erodes trust. To this end, we provide a multi-modal benchmark ConBench, to intuitively analyze how LVLMs perform when the solution space of a prompt revolves around a knowledge point.
|        Rank         |         Teacher         | ConScore[D] |
| :--------------------: | :---------------------: | :------: |
| 1 | Qwen-VL-Max |  37.00   |
|  2  |  GPT-4-Omni  |   35.70   |
|  3  |    InternVL-v1.2P-40B    |   34.70   |
|  4  |    Gemini-Ultra-Vision    | …
=> add Conbench

lmms_eval/tasks/mmupd/mmupd.yaml, lmms_eval/tasks/mmupd/mmupd_base.yaml, lmms_eval/tasks/mmupd/mmupd_instruction.yaml, lmms_eval/tasks/mmupd/mmupd_option.yaml
Hi! 
I have updated gpt-3.5-turbo version from `gpt-3.5-turbo-0613` to `gpt-3.5-turbo-0125` since `gpt-3.5-turbo-0613` will be deprecated.   
I confirmed that the results do not change by testing with the original UPD codebase.
So could you please merge this?
Thank you.
=> update gpt-3.5-turbo version

lmms_eval/models/llava_vid.py, lmms_eval/tasks/longvideobench/longvideobench_val_i.yaml, lmms_eval/tasks/longvideobench/longvideobench_val_v.yaml, lmms_eval/tasks/longvideobench/utils.py
[LongVideoBench](https://longvideobench.github.io) is the first interleaved video-language benchmark on up-to-hour-long videos.
Created two new tasks:
- longvideobench_val_i (for Image LMMs, e.g. LLaVA, Phi3v, Idefics2, default 16 frames)
- longvideobench_val_v (for Video LMMs, e.g. LLaVA-NeXT-Video, Video-LLaVA)
This difference is based on the different behaviours of Image and Video LMMs in current lmms-eval library, that image LMMs accept PIL.Image (s) as inputs, and video LMMs accept video paths. 
- Idefics2
```
python3 -m accelerate.commands.launch --num_processes=8 -m lmms_eval --model idefics2 --tasks longvideobench_val_i --batch_size 1 --log_samples --log_samples_suffix idefics2_lvb_i --output_path ./logs/
```
- Phi3V
```
python3 -m accelerate.commands.launch --num_processes=8 -m …
```
=> LongVideoBench for LMMs-Eval

lmms_eval/api/task.py, lmms_eval/models/llava_vid.py
In the previous commit, I have commented the L408 (stopping_criteria for generation) in https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/main/lmms_eval/models/llava_vid.py#L408C22-L408C39 to fit this model with transformers >4.40.2.  (The `stopping_criteria` still works with transformers==4.40.0)
Though this does not affect MCQ accuracy, no stopping criteria may potentially lead to risk on open-ended answers. Henceforth, a more responsible way is to remove this comment here.
I also include the lmms_eval/api/task.py to allow extracting videos from tars (which will make automatic evaluation of LongVideoBench really works from a brand new machine).
=> Fix the potential risk by PR #117

lmms_eval/tasks/gqa_ru/gqa_ru.yaml, lmms_eval/tasks/gqa_ru/utils.py
This PR adds gqa-ru, a translated version of original gqa. 
https://huggingface.co/datasets/deepvk/GQA-ru
=> add task gqa-ru

lmms_eval/tasks/mmbench/_default_template_mmbench_ru_yaml, lmms_eval/tasks/mmbench/mmbench.yaml, lmms_eval/tasks/mmbench/mmbench_ru_dev.yaml, lmms_eval/tasks/mmbench/ru_utils.py
This PR adds MMBench-ru, a translated version of original MMBench-ru.
https://huggingface.co/datasets/deepvk/MMBench-ru
Result for llava-v1.6-mistral-7b-hf, without requests to GPT
=> add task MMBench-ru

README.md
This pull request fixes a broken hyperlink in the README.md file.   
The original hyperlink was pointing to a file that no longer exists.   
The updated link now correctly points to the task documentation.   
=> [Docs] Fix broken hyperlink in README.md

lmms_eval/models/llava_hf.py
In the current version, the response separation occurs by a line specific to each model, which does not allow for testing many models. Additionally, some models have confusion with eos/eot, for which the ability to specify eos_token_id in the generation has been added.
=> Changes in llava_hf.py. Corrected the response split by role and added the ability to specify an EOS token

lmms_eval/tasks/seedbench_2/seedbench_2.yaml
Since there're only `model_specific_prompt_kwargs` for `llava` and `gpt4v` in `seedbench2.yaml`, attempting to evaluate other models resulted in a `TypeError: 'NoneType' object is not subscriptable` error due to the absence of this argument.
So I simply added default prompts in `seedbench2.yaml`.
=> Add default prompt for seedbench_2.yaml

lmms_eval/models/internvl.py, lmms_eval/models/internvl2.py, lmms_eval/tasks/scienceqa/utils.py
I found some issues during I evaluate InternVL and InternVL2 on ScienceQA task.
1. Errors in `generate_until()`
- When the input w/o any visual comes in, `generate_until` returns `IndexError` because they assume there must be at least one image in the input. So I fixed it.
2. Result processing code in SQA
- Missing `strip().lower()`
=> Fixed some issues in InternVL family and ScienceQA task.

docs/current_tasks.md, lmms_eval/tasks/seedbench_2_plus/seedbench_2_plus.yaml, lmms_eval/tasks/seedbench_2_plus/utils.py
1. Add SEEDBench 2 Plus Dataset:
Added the SEEDBench 2 Plus dataset proposed in the [paper](https://arxiv.org/abs/2404.16790), which already implemented in VLMEvalKit.
2. Rename Existing SEEDBench 2 Task Names:
Changed the task names in the existing SEEDBench 2 dataset from hyphens (-) to underscores (_) to maintain consistency with other datasets. (seedbench-2 -> seenbench_2)
3. Add Descriptions for seedbench 2 plus:
Added descriptions for seedbench 2 plus
I have completed tests for SEEDBench 2 Plus benchmark  on several models with this code change, but please leave a comment if further review is needed.
The data uploaded to the [datasets repository](https://huggingface.co/datasets/doolayer/SEED-Bench-2-Plus) was created with the following code:
```
data_json_fname = …
```
=> [Add Dataset] SEEDBench 2 Plus

docs/task_guide.md, lmms_eval/tasks/ai2d/ai2d_lite.yaml, lmms_eval/tasks/chartqa/chartqa_lite.yaml, lmms_eval/tasks/docvqa/docvqa_val_lite.yaml, lmms_eval/tasks/gqa/gqa_lite.yaml, lmms_eval/tasks/infovqa/infovqa_val_lite.yaml, lmms_eval/tasks/mirb/mirb.yaml, lmms_eval/tasks/mirb/utils.py, lmms_eval/tasks/mmbench/mmbench_cn_dev_lite.yaml, lmms_eval/tasks/mmbench/mmbench_en_dev_lite.yaml, lmms_eval/tasks/ok_vqa/ok_vqa_val2014_lite.yaml, lmms_eval/tasks/seedbench_2_plus/seedbench_2_plus.yaml, lmms_eval/tasks/textcaps/textcaps_val_lite.yaml, lmms_eval/tasks/textvqa/textvqa_val_lite.yaml, lmms_eval/tasks/vibe_eval/utils.py, lmms_eval/tasks/vizwiz_vqa/vizwiz_vqa_val_lite.yaml, lmms_eval/tasks/vqav2/vqav2_val_lite.yaml
=> fix: update from previous model_specific_prompt to current lmms_eval_kwargs to avoid warnings

docs/commands.md, docs/run_examples.md, lmms_eval/models/srt_api.py
---
This PR is to support sglang srt model to evaluate llava in one command. Now no longer needs to use a separate command to set up the backend server. An example command would be the following
```bash
CKPT_PATH=$1
TASK=$2
MODALITY=$3
TP_SIZE=$4
echo $TASK
TASK_SUFFIX="${TASK//,/_}"
echo $TASK_SUFFIX
python3 -m lmms_eval \
--model srt_api \
--model_args modality=$MODALITY,model_version=$CKPT_PATH,tp=$TP_SIZE,host=127.0.0.1,port=30000,timeout=600 \
--tasks $TASK \
--batch_size 1 \
--log_samples_suffix $TASK_SUFFIX \
--output_path ./logs/
```
Also, the PR uses async to submit request to sglang server so that requests can be processed in …
=> [Feat] SGLang SRT commands in one go, async input for openai server

lmms_eval/models/llava_onevision.py
Support text-only inference for LLaVA-OneVision. This attribute is required in benchmark like MathVerse Text Only version.
=> Support textonly inference for LLaVA-OneVision.

lmms_eval/api/task.py, lmms_eval/tasks/videomme/utils.py
This minor fix for `videomme` evaluation makes sure that videos are downloaded to and loaded from the correct folder.
=> Fix `videomme` evaluation

lmms_eval/api/metrics.py, lmms_eval/evaluator.py
=> [Fix] Fix bugs in returning result dict and bring back anls metric

lmms_eval/evaluator.py
This pull request adds a check for the existence of the accelerator before waiting. Previously, the code would attempt to wait for the accelerator without checking if it exists, which could lead to errors. With this change, the code will only wait for the accelerator if it is present, ensuring smoother execution.
=> [feat] Add check for existence of accelerator before waiting

lmms_eval/api/task.py, lmms_eval/evaluator.py, lmms_eval/tasks/arc/README.md, lmms_eval/tasks/arc/arc_challenge.yaml, lmms_eval/tasks/arc/arc_easy.yaml, lmms_eval/tasks/mmlu_pro/README.md, lmms_eval/tasks/mmlu_pro/_default_template_yaml, lmms_eval/tasks/mmlu_pro/_mmlu_pro.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_biology.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_business.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_chemistry.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_computer_science.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_economics.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_engineering.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_health.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_history.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_law.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_math.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_other.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_philosophy.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_physics.yaml, lmms_eval/tasks/mmlu_pro/mmlu_pro_psychology.yaml, lmms_eval/tasks/mmlu_pro/utils.py, pyproject.toml
This pull request adds LMMS evaluation tasks for various subjects, including law, math, other, health, biology, history, physics, business, chemistry, economics, philosophy, and psychology. Each task consists of multiple-choice questions with answers, and each task has a corresponding description and process documentation.
Remove unused LM object if model is not an instance of LM
=> add more language tasks and fix fewshot evaluation bugs

lmms_eval/api/samplers.py, lmms_eval/api/task.py, lmms_eval/tasks/mmmu/utils_group_img.py
1. Fix the shallow copy issue by force to deep copy every single `gen_kwargs` variables #224 
2. Fix a small bug in `Seed Bench`
=> [fix] Shallow copy issue

lmms_eval/models/srt_api.py
---
As stated in #243 , there is an error in current asyncio srt model. This PR tries to fix this and reproduce the result
=> [Fix] Fix async append result in different order issue

lmms_eval/tasks/wild_vision_bench/_default_template_yaml, lmms_eval/tasks/wild_vision_bench/utils.py
This pull request adds a new metric called "raw_scores" to the wildvision bench. The raw score represents the score of each result without any aggregation or transformation. It is calculated based on the "score" field in the results. The raw score is then used in the aggregation functions for further analysis. This addition provides more flexibility in analyzing and comparing the results.
=> Add raw score to wildvision bench

lmms_eval/models/srt_api.py
Current video loading tools seem to be slow when using async, this might cause the process looks like it is stucked. This PR restrict the model to use OpenAI server instead of AsyncOpenAI when evaluating video tasks
=> [Fix] Strict video to be single processing

lmms_eval/tasks/videomme/utils.py
correct video path in videomme_dic_to_text+subtitle
=> [Minor] Update utils.py

lmms_eval/api/task.py, lmms_eval/caching/cache.py, lmms_eval/evaluator.py
=> Refactor distributed gathering of logged samples and metrics

lmms_eval/models/__init__.py, lmms_eval/models/minimonkey.py
This PR intends to enhance the functionality of lmms-eval by supporting MiniMonkey model in Monkey series, which is not covered in latest version.
=> [Model] support minimonkey model

docs/commands.md, lmms_eval/__main__.py, lmms_eval/evaluator.py, lmms_eval/loggers/evaluation_tracker.py, lmms_eval/utils.py, tools/regression.py
This pull request adds new output_path saving logic and a regression test. The new logic ensures that the model's results are saved to the correct output path. Additionally, a regression test has been added to verify that the model's performance is not degraded after each pull request.
=> [Feat] add regression test and change saving logic related to `output_path`

lmms_eval/models/llava_hf.py
This PR update the `llava_hf` to enable the evaluation of the `llava_hf` on new series of llava model such as llava-onevision and llava-next(stronger). This PR also enable the video evaluation using llava_hf.
Noted that the video evaluation is only supported using llava onevision hf and would possibly failed if you other version of llava. Since the newest transformers version has not released you have to do
```bash
pip install git+https://github.com/huggingface/transformers.git
```
to install the transformers version from source if you want to use llava onevision hf.
However, after experiment, I think the performance still has some significance difference compare to the original llava. Thus, you are not recommended to use this model to get results of original llava or llava-onevision. …
=> [Feat] Add support for llava_hf video, better loading logic for llava_hf ckpt

lmms_eval/models/__init__.py, lmms_eval/models/cogvlm2.py
This PR intends to enhance the functionality of lmms-eval by supporting CogVLM2 model, which is not covered in latest version.
The code is evaluated with mmstar dataset. Here is the screeshot as follows:
=> [Model] support cogvlm2 model

lmms_eval/models/gpt4v.py
API errors should return an empty string instead of the answer from the previous query.
=> [Bug] Fix the checking error in gpt4v generation

lmms_eval/models/gemini_api.py
When evaluating large video datasets, sometimes the total size of the videos exceeds the 20 GB limit. Therefore, during evaluation, it's necessary to delete unnecessary videos while running the process.
=> [fix] Refactor GeminiAPI class to add video pooling and freeing

docs/task_guide.md
Note:
Bring the configurations to the front, and add an example YAML configuration file to explain the variables `doc_to_text`, and its usage on embedded Python function.
More Todos (with incoming PRs):
1. Find tasks with integrated metrics that can be abstract to define in `api/metrics.py` instead of putting in each task's `utils.py`. For example, `wer` is not defined in `librispeech` and it should be defined in `api/metrics.py` in the future.
2. Better guide on integrating new tasks, better guide on debugging code for crashes and non-executable cases.
=> [Doc] add more detailed task guide to explain the variables in yaml configuration file

lmms_eval/tasks/mmsearch/mmsearch.yaml
- Group in `mmsearch.yaml` is invalid (`mathverse`), so it cause an error when you trying to evaluate mathverse.
=> [fix] Invalid group in mmsearch.yaml

lmms_eval/tasks/live_bench/live_bench.yaml, lmms_eval/tasks/live_bench/live_bench_template_yaml_v2, lmms_eval/tasks/live_bench/utils_v2.py, tools/live_bench/live_bench/data_generator/live_bench_data.py, tools/live_bench/script/change.ipynb, tools/live_bench/script/update_banchmark.ipynb
=> [Fix] Change "Basic Understanding" to "Concrete Recognition"

lmms_eval/models/__init__.py, lmms_eval/models/llama_vision.py, lmms_eval/models/qwen_vl_api.py
=> [Feat] LLaMA-3.2-Vision

lmms_eval/tasks/vinoground/utils.py, lmms_eval/tasks/vinoground/vinoground.yaml
Hi, I want to add our video benchmark [Vinoground](https://vinoground.github.io) to the lmms-eval database. This temporal counterfactual benchmark contains 1000 short and natural video-caption pairs. The best model, GPT-4o, can only perform at 35% on one of our metrics, while humans can achieve ~90% at ease. I have been able to reproduce our results with the code provided here on LLaVA-Video-7B-Qwen2. I believe that more models should be allowed to evaluate on Vinoground to truly test their dense temporal reasoning capabilities, and hence i find lmms-eval a great platform to do so.
=> add vinoground

lmms_eval/evaluator.py
Downloading datasets before loading models will help prioritise data preparation without using GPUs.
- just adjusted the order of the code in evaluator.py
- it has been tested for most of the datasets for single-image and text-only scenarios and no anomalies were found
=> Update evaluator.py to load datasets first before loading models

lmms_eval/models/llava_onevision.py
- Configuration rollback has been added to avoid errors on evaluation benchmarks with a mix of single and multiple images such as MMMU, SEEDBench, etc.
- Original code will override the original `image_aspect_ratio` by [this line](https://github.com/LooperXX/lmms-eval/blob/2378120f3e054415cc5f9f2741e1030405a722de/lmms_eval/models/llava_onevision.py#L433). This behaviour appears in `loglikelihood`, `generate_until` and `generate_until_multi_round` functions. 
- Such overriding behaviour will result in the `image_aspect_ratio` of all single-image samples encountered after multiple-image samples being overridden by e.g. `pad` on benchmarks with both single-image and multiple-image samples.
=> Update llava_onevision.py to avoid erros on evaluation benchmarks with both single- and multi-image samples.

lmms_eval/tasks/cinepile/cinepile.yaml, lmms_eval/tasks/cinepile/utils.py
CinePile is a question-answering-based, long-form video understanding dataset. It has been created using advanced large language models (LLMs) with human-in-the-loop pipeline leveraging existing human-generated raw data. It consists of approximately 300,000 training data points and 5,000 test data points.
=> Upload Tasks: CinePile

lmms_eval/tasks/cuva/_default_template_yaml, lmms_eval/tasks/cuva/cuva.yaml, lmms_eval/tasks/cuva/cuva_test.yaml, lmms_eval/tasks/cuva/utils.py, lmms_eval/tasks/funqa/_default_template_yaml, lmms_eval/tasks/funqa/funqa.yaml, lmms_eval/tasks/funqa/funqa_test.yaml, lmms_eval/tasks/funqa/utils.py
=> funqa update

lmms_eval/tasks/vinoground/utils.py, lmms_eval/tasks/vinoground/vinoground.yaml
As mentioned by Issue #350, the results of video score and group score on many models are inconsistent with the original paper. This is because in the lmms-eval code we initially provided, we did not use the shuffled questions like we did in the paper. We update the code to correctly reflect that and we are now able to reproduce results on llava-ov-qwen2-7b.
=> Update Vinoground to make evaluation consistent with paper

README.md, docs/current_tasks.md
update docs for VDC and MovieChat includings
1. announcements section in README.md
2. add comment and fix issue in current_tasks.md
=> update docs for VDC and MovieChat

lmms_eval/api/task.py, lmms_eval/tasks/llava-in-the-wild/llava-in-the-wild.yaml, lmms_eval/tasks/llava-in-the-wild/utils.py, lmms_eval/tasks/mathverse/mathverse_evals.py, lmms_eval/tasks/mathvista/mathvista_evals.py, lmms_eval/tasks/mathvista/utils.py, lmms_eval/tasks/mmvet/utils.py
- update to be compatible with Azure's GPT4/4o as judge model.
=> [WIP] feat: update to use azure api

lmms_eval/tasks/mlvu/utils.py
This PR updates the `extract_characters_regex` function in MLVU to improve parsing robustness. Previously, formats like ‘A.’ were incorrectly parsed as wrong answers when the ground truth was ‘A’. The function now follows the VideoMME style for improved handling.
=> Update MLVU answer parsing

lmms_eval/tasks/mathverse/mathverse_evals.py
=> Add os import to mathverse_evals.py

lmms_eval/models/llava_hf.py
=> [Fix] llava_hf generate until issue

README.md, docs/current_tasks.md, lmms_eval/tasks/temporalbench/temporalbench.yaml, lmms_eval/tasks/temporalbench/temporalbench_long_qa.yaml, lmms_eval/tasks/temporalbench/temporalbench_short_caption.yaml, lmms_eval/tasks/temporalbench/temporalbench_short_qa.yaml, lmms_eval/tasks/temporalbench/utils.py, pyproject.toml
Hi lmms team,
I want to add our video benchmark [TemporalBench](https://temporalbench.github.io/) to the lmms-eval database. is a video understanding benchmark designed to evaluate fine-grained temporal understanding and reasoning for multimodal video models. It consists of ∼10K video question-answer pairs sourced from ∼2K high-quality human-annotated video captions, capturing detailed temporal dynamics and actions.
=> Add TemporalBench

lmms_eval/api/task.py
It seems that `dataset_kwargs is not None` was lacked.
=> [Tiny Fix] fix dataset_kwargs in lmms_eval/api/task.py

README.md
Update NaturalBench to README.md
=> [update] NaturalBench to README

docs/run_examples.md, lmms_eval/models/__init__.py, lmms_eval/models/aria.py, lmms_eval/models/slime.py, lmms_eval/tasks/mme_realworld/mme_realworld.yaml, lmms_eval/tasks/mme_realworld/mme_realworld_lite.yaml, lmms_eval/tasks/mme_realworld/utils.py
This pull request introduces two key updates:
1. **Added the [Slime](https://github.com/yfzhang114/SliME) model**.
2. **Updated the download link for MME-RealWorld**, and added a new version, **[MME-RealWorld-lite](https://huggingface.co/datasets/yifanzhang114/MME-RealWorld-lite-lmms-eval)**, which samples 50 instances per task from [MME-RealWorld](https://github.com/yfzhang114/MME-RealWorld) for inference acceleration.
Below are the performance results of the Slime model, along with other models, on the MME-RealWorld-lite dataset.
| Method      | LLM          | Overall | Perception |   |   |   |   |    | Reasoning |   |   |   |   |
|-------------|--------------|---------|------------|---|---|---|---|----|-----------|---|---|---|---|
|             |              |         | OCR        | …
=> add model Slime and Benchmark mme_realworld_lite

lmms_eval/tasks/mia_bench/mia_bench.yaml, lmms_eval/tasks/mia_bench/utils.py
MIA-Bench is from Apple and used to evaluate multimodal models instruction following abilities.
Homepage: https://github.com/[apple/ml-mia-bench](https://github.com/apple/ml-mia-bench)
HF Dataset: https://huggingface.co/datasets/lmms-lab/MIA-Bench
✨ feat(mia_bench): introduce new MIA-Bench task configuration and utilities
- add mia_bench.yaml for task configuration with dataset and evaluation settings
- implement utility functions for document processing and result generation
- integrate OpenAI and Azure API support for evaluation
- provide aggregation functions to calculate overall scores
```sh
```
=> [Task] add MIA-Bench

lmms_eval/models/gemini_api.py
=> Gemini Audio

lmms_eval/models/llama_vision.py
BugFix: llama_vision processor accepts "text" key and not "content" key.
In the current implementation the processor accepts the messages variable with a "content" field:
`messages[-1]["content"].append({"type": "text", "content": contexts})`
But this is not the correct format for llama vision, and for example when this is the messages variable:
```
(Pdb) messages
[{'role': 'user', 'content': [{'type': 'image'}, {'type': 'text', 'content': "<image 1> Baxter Company has a relevant range of production between 15,000 and 30,000 units. The following cost data represents average variable costs per unit for 25,000 units of production. If 30,000 units are produced, what are the per unit manufacturing overhead costs incurred?\nA. $6\nB. $7\nC. $8\nD. $9\n\nAnswer with the option's letter from the …
```
=> BugFix: Fixed input to llama_vision processor

lmms_eval/tasks/mmvetv2/mmvetv2.yaml, lmms_eval/tasks/mmvetv2/mmvetv2_group_img.yaml, lmms_eval/tasks/mmvetv2/utils.py
MM-Vet v2 is a extension of MMVet, which includes a new VL capability called "image-text sequence understanding", evaluating models' ability to process VL sequences.
paper: https://arxiv.org/abs/2408.00765
github: https://github.com/yuweihao/MM-Vet/tree/main/v2
Since the sample may have multiple images, it is provided mmvetv2_group_img.yaml for those models that cannot handle multiple image inputs.
=> add task MMVet-v2

lmms_eval/tasks/mmt/utils.py
Updated the mmt_aggregate_results function to return only the overall accuracy while logging the category-wise accuracies using eval_logger instead of returning them.
=> Fix mmt output format

lmms_eval/models/aria.py, lmms_eval/tasks/videofinal/utils.py, lmms_eval/tasks/videommmu_engineering_1206/utils.py, lmms_eval/tasks/videosearch/utils.py
=> [Fix] Update Aria from extraction

lmms_eval/models/gemini_api.py, lmms_eval/models/text.ipynb, lmms_eval/tasks/av_odyssey/av_odyssey.yaml, lmms_eval/tasks/av_odyssey/utils.py
We introduce the av_odyssey benchmark, designed to evaluate a model's audio-visual capabilities.
Currently, we provide an implementation based on the Gemini model. The corresponding command to run the evaluation is as follows:
```shell
accelerate launch --num_processes 8 --main_process_port 12345 -m lmms_eval --model gemini_api --tasks av_odyssey --batch_size 1  --log_samples_suffix av_odyssey --output_path ./logs/
```
To support this evaluation, we made modifications to the gemini_api.py file located in the models directory.
=> add av_odyssey bench

lmms_eval/models/internvl2.py
…apping in InternVL2 class
```sh
```
=> Fix InternVL2 model sharding

lmms_eval/evaluator.py
This PR solves an OOM issue when evaluating large models (e.g., 34B or 72B) on multiple GPUs.
- The model inference and result postprocessing can successfully complete, but multigpu data gathering to rank 0 (or any other any) cause the OOM issue.
This PR moves the model and cache deletion before the multrgpu data gathering to save the GPU memory.
=> Delete model and cache before multigpu data gathering

lmms_eval/models/gemini_api.py
…ing content variable
```sh
```
=> Fix Gemini

lmms_eval/models/gemini_api.py, lmms_eval/models/internvl2.py
This PR fixes two minor errors in models.
- When we use `GeminiAPI` with `continual_mode=False`, It causes ValueError since `self.response_persistent_file` is not declared.
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/8821357aa338a17b94102118cbb5c8b94f594ae0/lmms_eval/models/gemini_api.py#L58-L64
- So I initialized `self.response_persistent_file` with an empty string (`""`) to prevent error.
- In `internvl2.py`, `self.model.chat()` in line 316 requires `num_patches_list` variable.
- But in line 315, we declare `num_patch_list` instead of `num_patches_list`.
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/8821357aa338a17b94102118cbb5c8b94f594ae0/lmms_eval/models/internvl2.py#L313-L316
- This seems a typo error, so I fixed it.
BTW, Happy New Year!
=> [FIX] Minor errors in `gemini_api.py` and `internvl2.py`.

lmms_eval/models/llava.py, lmms_eval/models/llava_onevision.py, lmms_eval/models/tinyllava.py
This PR resolves a `NoneType` iteration error in the `flatten` function when handling text-only tasks (e.g., MMLU or HellaSwag) in LLAVA family models.
The `flatten` function processes batched visual tokens but receives `None` or empty inputs in text-only tasks. This leads to a `NoneType` iteration error in the original implementation.
1. Added input validation to `flatten`:
- Checks if the input is `None` or empty.
- Returns an empty list if validation fails.
2. Ensures sub-elements are validated before iteration.
This update ensures compatibility with text-only tasks while maintaining functionality for visual tasks.
=> Fix NoneType Error in `flatten` Function for Text-Only Tasks in LLAVA Models

lmms_eval/evaluator.py
quickfix to enable the usage of already instances lmms models, similar to the behavior of lm_eval
=> Fix custom model wrapper to enable usage of instanced model

lmms_eval/tasks/air_bench/utils.py, lmms_eval/tasks/vocalsound/utils.py
separately print categorical accuracy so it does not mess up the table
=> fix output format of airbench and vocal sound

lmms_eval/tasks/megabench/README.md, lmms_eval/tasks/megabench/evaluator.py
This PR fixes the metric type determination in megabench's evaluator, and refines the readme. 
---
```sh
```
=> [Fix] megabench evaluator metric type determination

lmms_eval/tasks/covost2/_default_template_zh_en_yaml, lmms_eval/tasks/covost2/covost2_zh_en_dev.yaml, lmms_eval/tasks/covost2/covost2_zh_en_test.yaml, lmms_eval/tasks/covost2/utils.py
aggregation function was using the same "zh" tokenizer in the aggregate function for both en and zh
=> fix aggregation function and remove redundancies

lmms_eval/api/metrics.py, lmms_eval/api/registry.py, lmms_eval/api/task.py, lmms_eval/evaluator_utils.py, lmms_eval/filters/selection.py, lmms_eval/models/qwen2_vl.py, lmms_eval/tasks/mmlu/flan_n_shot/generative/_mmlu.yaml, lmms_eval/tasks/mmmu/mmmu_val_pass64.yaml, lmms_eval/tasks/mmmu/mmmu_val_reasoning.yaml, lmms_eval/tasks/mmmu/utils.py, miscs/cicd_qwen2vl.sh
With this PR, we fixed two problems:
1. Display the group results for `mmlu_flan_n_shot_generative` by changing the `acc` to `exact_match` since `acc` will result the group display not matched in evaluation metrics.
2. Introduce the @maj and @pass mechanisms to enable majority voting and multi-pass evaluation. In this mode, the model generates multiple response samples for a given question. The final correctness is determined either through majority voting (@maj), where the most frequently occurring answer is selected as the final output, or through multi-pass evaluation (@pass), where the presence of at least one correct response across the generated samples is sufficient to deem the final output correct.
=> [Feat] add @maj and @pass to support sampling multiples times during evaluation

README.md
This PR fixes the bug of evaluation of llava_vid in the README.
The possible reason is that the model names do not match. [llavavid](https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/main/README.md?plain=1#L197) in the README, but [llava_vid](https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/main/lmms_eval/models/__init__.py#L32) in lmms_eval/models /__init__.py.
```
```
```sh
```
=> [Fix] of "Model llavavid not found in available models."

.gitignore, lmms_eval/models/__init__.py, lmms_eval/models/openai_compatible.py, miscs/model_dryruns/openai_compatible.sh
Update API usage and add environment configuration
- Add new `OpenAICompatible` model class to support more variants models as long as they support openai format API.
- Update `.gitignore` to exclude `.env` and `scripts/`.
.gitignore:
- Exclude `.env` file for security.
- Ensure no scripts directory is tracked.
lmms_eval/models/gpt4v.py:
- Refactor API client initialization to use new OpenAI and Azure clients.
- Update image encoding to handle size limits with resizing logic.
- Adjust retry logic for API calls, reducing sleep time.
=> [Model] add openai compatible API interface

lmms_eval/tasks/mmstar/utils.py
Changed the string processing order from `lower().strip().replace('\n', ' ')` to `lower().replace('\n', ' ').strip()`.
1. In the current order, after `strip()` followed by newline-to-space conversion, newlines at the beginning or end of the string are converted to spaces but remain in the string.
2. The modified order first converts newlines to spaces, then removes all leading and trailing whitespace at once, resulting in cleaner output.
3. This ensures more consistent output especially when processing multi-line inputs.
=> [Evaluation] Improve string processing order for better whitespace handling

lmms_eval/models/ola.py
=> Fix Ola path for GPUs

lmms_eval/tasks/livexiv_tqa/livexiv_tqa.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_template_yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v1.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v2.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v3.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v4.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v5.yaml, lmms_eval/tasks/livexiv_tqa/livexiv_tqa_v6.yaml, lmms_eval/tasks/livexiv_tqa/utils.py, lmms_eval/tasks/livexiv_vqa/livexiv_vqa.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_template_yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v1.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v2.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v3.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v4.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v5.yaml, lmms_eval/tasks/livexiv_vqa/livexiv_vqa_v6.yaml, lmms_eval/tasks/livexiv_vqa/utils.py
Add LiveXiv benchmark
https://huggingface.co/datasets/LiveXiv/LiveXiv
Pre-commit passed
Added according to live_bench scheme
=> Add LiveXiv benchmark [ICLR 2025]

lmms_eval/tasks/vmcbench/utils.py, lmms_eval/tasks/vmcbench/vmcbench.yaml
Thanks for the great repo! This pull request provides minimal code implementation to support the VMCBench dataset. 
VMCBench is from "Automated Generation of Challenging Multiple-Choice Questions for Vision Language Model Evaluation" (CVPR 2025) [https://yuhui-zh15.github.io/AutoConverter-Website/](https://github.com/open-compass/VLMEvalKit/pull/url). 
VMCBench is created by transforming 20 existing VQA datasets into a unified multiple-choice format, totaling 9,018 questions. Using VLMEvalKit, we comprehensively evaluate 28 state-of-the-art VLMs on VMCBench, setting a new standard for scalable, consistent, and reproducible VLM evaluation.
We have carefully tested this pull request and performed code linting.
------
Running command:
```markdown
python -m accelerate.commands.launch \ …
```
=> [Dataset] Support VMCBench (CVPR 25)

docs/task_guide.md, lmms_eval/tasks/multimodal_rewardbench/multimodal_rewardbench.yaml, lmms_eval/tasks/multimodal_rewardbench/utils.py
```sh
```
---
This benchmark is created by Yasunaga et al. (2025).
📄 Paper: [Multimodal RewardBench: Holistic Evaluation of Reward Models for Vision Language Models](https://arxiv.org/abs/2502.14191)
💻 GitHub Repository: https://github.com/facebookresearch/multimodal_rewardbench
Currently, the `dataset_path` is "syhuggingface/multimodal_rewardbench."
I uploaded the dataset to Hugging Face for easy access.
I have downloaded the original data from the GitHub repo and only modified the "Image" attribute by …
=> [Add] Task "Multimodal RewardBench"

lmms_eval/tasks/mme_cot/mme_cot_reason.yaml, lmms_eval/tasks/mme_cot/utils.py
* Introduced a new metric `llm_as_judge_eval` in `mme_cot_reason.yaml` for evaluating solutions using LLM.
* Updated `utils.py` to include functions for generating prompts and retrieving responses from GPT-4o.
* Enhanced result processing to incorporate LLM judgments alongside existing predictions.
```sh
```
=> [Enhancement] Add LLM evaluation metric and integrate GPT-4o reasoning

lmms_eval/models/qwen2_5_vl.py
Hello, noticed that there was a hard-coded number of max_new_tokens in qwen2_5_vl model provided.
=> Fix hard-coded max_new_tokens for qwen2_5_vl model

lmms_eval/tasks/omni_bench/_default_template_yaml, lmms_eval/tasks/omni_bench/omni_bench.yaml, lmms_eval/tasks/omni_bench/omni_bench_audio_transcript.yaml, lmms_eval/tasks/omni_bench/omni_bench_image_caption.yaml, lmms_eval/tasks/omni_bench/utils.py
Add Omni Bench with 3 settings:
- Original
- Replace audio with provided audio transcript ( for vlm)
- Replace image with provided image caption (for alm)
During evaluation, there are 12 samples that soundfile unable to load the audio.
I try to work around this but cannot fix. Hence I remove those samples and upload to lmms-lab/Omni_Bench_fix. The full set is at lmms-lab/Omni_Bench. The original has 1342 samples, the fixed one has 1330 samples.
=> Add Omni Bench

docs/current_tasks.md, lmms_eval/tasks/megabench/README.md, lmms_eval/tasks/megabench/metrics/metric_type.py
This PR fixes MEGA-Bench's evaluator to handle some corner cases where the responses with unexpected formats can break up the metric. This usually only happens for small models (<7B) or old models with poor instruction-following capacity. The doc is also updated.
---
```sh
```
=> [Feat] Fix MEGA-Bench evaluator, update doc

lmms_eval/models/__init__.py, lmms_eval/models/vora.py
This PR introduces support for [VoRA](https://arxiv.org/abs/2503.20680), a novel paradigm for transforming an LLM into an MLLM. 
Below is a screenshot of the evaluation result on realwordqa task:
=> [Model] support VoRA model

lmms_eval/models/qwen2_5_vl.py
Hello, for some reason by default Qwen2.5 models don't have correct padding side set, which prevents them from running with flash_attention enabled
=> [Fix] Add padding_side="left" for Qwen2.5 to enable flash_attention

lmms_eval/models/vllm.py
This pull request enables passing options to VLLM directly. This is useful for the following scenario:
1. gemma-3-12b-it model, which can fit in 2x24G GPU, but has a long-context of 128k tokens. User can then specify max_model_len directly like:
```VLLM_USE_V1=0 VLLM_WORKER_MULTIPROC_METHOD=spawn lmms-eval --tasks mmmu --model vllm --model_args model_version=google/gemma-3-12b-it,tensor_parallel_size=2,gpu_memory_utilization=0.95,max_images=1,max_videos=0,max_audios=0,max_model_len=4096 --batch_size 100 --log_samples --output_path lmms-results```
It enables support for all VLLM engine args.
=> Add ability to pass options to VLLM

lmms_eval/models/whisper_vllm.py, lmms_eval/tasks/fleurs/utils.py
This PR introduces fixes and enhancements to support accurate evaluation of Whisper models (via vLLM backend) on the FLEURS benchmark.
Task-Aware Prompt Injection for FLEURS:
- Detects if a task starts with fleurs and injects Whisper-style prompts based on the language field in the sample metadata. For example:
- <|zh|> for Mandarin and Cantonese (same token for both languages as using `yue` for Cantonese actually ends with worse `WER`)
- <|en|> for English (many whisper models do fine without a specific `en` token but some need it for e.g `openai/whisper-large-v3`)
- These prompts are crucial for Whisper’s multilingual ASR, as vLLM requires the correct prompt prefix to trigger language-specific decoding.
Fix character-level tokenization for Mandarin and Cantonese: 
- Replaces the …
=> Whisper + vLLM: FLEURS Evaluation Fixes and Language Prompt Injection

lmms_eval/api/task.py
If you want to load a dataset from a local location there were 2 bugs: 
- the kwargs you needed for a later call would get popped since a copy isn't made of the kwargs
-  Params for datasets.load_dataset were used instead of datasets.load_from_disk
Related to https://github.com/EvolvingLMMs-Lab/lmms-eval/pull/584
=> Fix loading datasets from disk

lmms_eval/caching/cache.py, lmms_eval/loggers/utils.py
Right now reading from cache returns stringified versions in case where object itself could be written. Raises error when values read out of the cache since str type not Instance type.
=> Cache stringifies where not needed

lmms_eval/tasks/VisualPuzzles/VisualPuzzles_cot.yaml, lmms_eval/tasks/VisualPuzzles/VisualPuzzles_direct.yaml, lmms_eval/tasks/VisualPuzzles/utils.py
```sh
```
VisualPuzzles is a benchmark that targets visual reasoning while deliberately minimizing reliance on specialized knowledge. VisualPuzzles consists of 1168 diverse questions spanning five categories: algorithmic, analogical, deductive, inductive, and spatial reasoning. Each puzzle is labeled as easy, medium, or hard. All puzzles are multiple-choice questions with 4 options.
Two evaluation prompts are included, one utilizing CoT [lmms_eval/tasks/VisualPuzzles/VisualPuzzles_cot.yaml](#lmms_eval/tasks …
=> [Task] Add support for VisualPuzzles

lmms_eval/models/aria.py, lmms_eval/models/llama_vision.py, lmms_eval/models/openai_compatible.py, lmms_eval/models/qwen2_5_vl.py, lmms_eval/models/qwen2_vl.py, lmms_eval/tasks/VisualPuzzles/utils.py, pyproject.toml
- Replaced AutoModelForCausalLM and AutoProcessor with AriaForConditionalGeneration and AriaProcessor in the Aria model.
- Updated the pretrained model string in LlamaVision to "meta-llama/Llama-3.2-11B-Vision-Instruct".
- Enhanced OpenAICompatible to support AzureOpenAI and modified API key handling for better flexibility.
- Adjusted timeout parameter and refined token handling in OpenAICompatible for improved functionality.
```sh
```
=> [Fix] Aria and LLama Vision and OpenAI compatible models

lmms_eval/models/qwen2_5_vl.py
Fix the bug: The images blending within the same batch leads to the performance degradation of Qwen2.5_VL when the batch size increases
After fixing:
- model: Qwen/Qwen2.5-VL-3B-Instruct
- task: vqav2_val_lite
- results: 
| Batch size | Performance | Total Time(s) |
|:---:|:---:|:---:|
| 1 | 0.7478 | 120.2 |
| 2 | 0.7490 | 109.9 |
| 4 | 0.7466 | 98.9 |
=> Fix the bug in issue #648

README.md, examples/models/aero_1_audio.sh, lmms_eval/models/__init__.py, lmms_eval/models/aero.py
🚀 Introducing Aero-1-Audio — a compact yet mighty audio model.
🧠 Built on Qwen-2.5-1.5B
⚡ Trained in <24h on just 16×H100
🎧 Handles 15+ min audio seamlessly
💡 Outperforms bigger models like Whisper, Qwen-2-Audio & commercial services from ElevenLabs/Scribe
Aero shows: smart data > massive scale.
Github Repo: https://github.com/EvolvingLMMs-Lab/Aero-1
Model Checkpoints: https://huggingface.co/lmms-lab/Aero-1-Audio-1.5B
Evaluation Results: https://github.com/EvolvingLMMs-Lab/lmms-eval/tree/dev/aero
Cookbook: https://www.lmms-lab.com/posts/lmms-lab-docs/aero_audio/
[20250424_092927_results.json](https://github.com/user-attachments/files/19959688/20250424_092927_results.json)
[20250421_203304_results.json](https://github.com/user-attachments/files/19959689/20250421_203304_results.json) …
=> [New Model] Aero-1-Audio

lmms_eval/models/vila.py
Catch import errors ASAP.
This is for debugging the VILA model, which returns error:
`Failed to import VILA from vila: VILA is not installed. Please install VILA to use this model. Error: cannot import name 'field_serializer' from 'pydantic'`
To reproduce the error, install VILA via:
```python
def install_vila(in_folder: str = "third-party"):
"""
Clone VILA into `in_folder`, append missing constants, and install.
"""
append_block = """\
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
"""
repo_dir = os.path.join(in_folder, "VILA")
target_file = os.path.join(repo_dir, "llava", "constants.py")
if not os.path.isdir(repo_dir):
subprocess.run(
f"git clone …
```
=> [improve]: catch import error; remove unused modules

lmms_eval/tasks/mathverse/mathverse_evals.py, lmms_eval/tasks/mathverse/utils.py
This PR addresses an issue in the MathVerse evaluation system where the scoring model fails to correctly judge answers for Vision-Only data.
Previously, when evaluating Vision-Only data, the question field was empty, causing the scoring model to fail when attempting to determine the correctness of answers following multiple-choice options.
**Before fix:**
```
[Question]: 
[Standard Answer]: B
[Model_answer]: yyy
Judgement: 0  # Incorrect scoring due to empty question field
```
**After fix:**
```
[Question]: As shown in the figure, circle O has a radius 1.0, if angle BAC = 60.0, then the length of BC is () A. xxx B. yyy
[Standard Answer]: B
[Model_answer]: yyy
Judgement: 1  # Correctly scored as matching
```
The fix ensures the correct key is used for question_for_eval, enabling proper …
=> [FIX]: Fix question_for_eval key in MathVerse evaluator for Vision-Only data

lmms_eval/tasks/capability/_default_template_yaml, lmms_eval/tasks/capability/capability.yaml, lmms_eval/tasks/capability/capability_OCR.yaml, lmms_eval/tasks/capability/capability_action.yaml, lmms_eval/tasks/capability/capability_camera_angle.yaml, lmms_eval/tasks/capability/capability_camera_movement.yaml, lmms_eval/tasks/capability/capability_character_identification.yaml, lmms_eval/tasks/capability/capability_dynamic_object_number.yaml, lmms_eval/tasks/capability/capability_event.yaml, lmms_eval/tasks/capability/capability_object_category.yaml, lmms_eval/tasks/capability/capability_object_color.yaml, lmms_eval/tasks/capability/capability_object_number.yaml, lmms_eval/tasks/capability/capability_scene.yaml, lmms_eval/tasks/capability/capability_spatial_relation.yaml, lmms_eval/tasks/capability/capability_style.yaml, lmms_eval/tasks/capability/prompt.py, lmms_eval/tasks/capability/utils.py
This pull request adds a new visual caption benchmark: CAPability.
[CAPability](https://github.com/ali-vilab/CAPability) evaluates the LMMs by around 11K human-annotated image/video-annotation pairs. Different from directly annotating ground-truth captions, we design 13 dimensions and annotate information for each dimension, and evaluate from these 13 dimensions, calculating precision, recall, and f1-score as metrics. See this [README](https://github.com/ali-vilab/CAPability/blob/main/README.md) for detailed introduction. Therefore, we create 1 default template yaml, 13 config yamls for each dimension, and 1 final grouped config yaml. The `utils.py` and `prompt.py` support the inference and evaluation process.
Check these links if you are interested in CAPability: …
=> [Task] Add new benchmark: CAPability

lmms_eval/models/qwen2_5_vl.py, lmms_eval/tasks/mathvision/utils.py
**Description :** 
This PR fixes a bug in MathVision evaluation and includes improvements to reproduce the MathVision evaluation for Qwen2.5-VL.
The current MathVision evaluation codebase breaks due to the following issues:
- The value for "until" is incorrectly set to "\n\n" by default, which causes the response to be truncated incorrectly.
[Reference](https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/a7b7c8dfc874fea13b8036741f456650e36a01ea/lmms_eval/models/qwen2_5_vl.py#L204)
- The mathvision_doc_to_text(doc) function needs to accept lmms_eval_specific_kwargs as an argument.
[Reference](https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/a7b7c8dfc874fea13b8036741f456650e36a01ea/lmms_eval/tasks/mathvision/utils.py#L95)
**Reproducing MathVision Results on Qwen2.5-3B-Instruct :**
The …
=> Mathvision bug fixes , Reproduce Qwen2.5VL results

lmms_eval/models/srt_api.py
PR to fix process killing in sglang.
`kill_child_process` is changed to `kill_process_tree` in sglang. [Reference](https://github.com/ravi03071991/sglang/blob/00c2c1f08b169c9239c77bf1dc5a97ea7d29d5e4/python/sglang/srt/utils.py#L697).
Thank You.
=> Fix issue with killing process in sglang

examples/models/plm.sh, lmms_eval/models/plm.py
This pull request fixes the issue of reading the following parameters from released PLM checkpoints:
1. `vision_input_type`
2. `max_num_tiles`
3. `video_max_frames`
These parameters are located under the `data` key in the released checkpoints, as opposed to the `model` key in the current implementation.
Please refer to the official checkpoints' `params.json` for more details:
1. [facebook/Perception-LM-1B/params.json](https://huggingface.co/facebook/Perception-LM-1B/blob/main/params.json#L36)
2. [facebook/Perception-LM-3B/params.json](https://huggingface.co/facebook/Perception-LM-3B/blob/main/params.json#L36)
3. [facebook/Perception-LM-8B/params.json](https://huggingface.co/facebook/Perception-LM-8B/blob/main/params.json#L34)
This change enables users to evaluate custom-trained PLM …
=> Fixes Metadata Reading from Released PLM Checkpoints

lmms_eval/tasks/vitatecs/utils.py
This pull request addresses an issue in the hand-crafted matching rules for VITATECS benchmark. The change fixes the extraction of the answer choice from the prediction string when it starts with prefixes like "(A)" or "(B)".
Old behavior incorrectly used the text after the closing parenthesis, which lead to incorrect rating.
New behavior extracts the second character of the prefix (e.g., "A" or "B").
=> [Fix] Correct rating logic for VITATECS benchmark

.gitignore, examples/models/qwen25vl.sh, pyproject.toml
- Updated Python version requirement in pyproject.toml to >=3.12.
- Removed specific version constraint for protobuf in dependencies.
- Added 'uv.lock' to .gitignore.
- Modified example script to change model task from 'mmmu_pro' to 'mme' and updated comments for clarity.
```sh
```
=> [fix] add reminder for `interleave_visual` for Qwen2.5-VL, update version control.

lmms_eval/__main__.py
The issue has been identified and fixed. The problem was in /opt/tiger/lmms-eval/lmms_eval/__main__.py:412 where task_manager.list_all_tasks() returns a formatted string, but the code was trying to
join it as if it were a list, resulting in each character being printed separately.
The fix was to change task_manager.list_all_tasks() to task_manager.all_tasks to get the actual list of task names.
```sh
```
=> [fix] Fix task listing in CLI evaluation by updating to use 'all_tasks' instead of 'list_all_tasks' for improved clarity.

.gitignore, examples/models/qwen25vl.sh, lmms_eval/models/qwen2_5_vl.py, lmms_eval/tasks/vlmsareblind/README.md, lmms_eval/tasks/vlmsareblind/__init__.py, lmms_eval/tasks/vlmsareblind/utils.py, lmms_eval/tasks/vlmsareblind/vlmsareblind.yaml, lmms_eval/tasks/vlmsareblind/vlmsareblind_lite.yaml, lmms_eval/tasks/vstar_bench/README.md, lmms_eval/tasks/vstar_bench/__init__.py, lmms_eval/tasks/vstar_bench/_default_template_yaml, lmms_eval/tasks/vstar_bench/utils.py, lmms_eval/tasks/vstar_bench/vstar_bench.yaml, lmms_eval/tasks/vstar_bench/vstar_bench_direct_attributes.yaml, lmms_eval/tasks/vstar_bench/vstar_bench_relative_position.yaml, pyproject.toml
V*-Bench is a visual question-answering benchmark designed to evaluate multimodal language models' capabilities in visual perception and reasoning. The benchmark focuses on assessing models' ability to accurately identify and reason about visual attributes in images through multiple-choice questions.
- **Dataset**: `lmms-lab/vstar-bench`
- **Size**: 191 test samples
- **Format**: Multiple-choice questions with 4 options (A, B, C, D)
- **Modalities**: Image + Text
The benchmark includes two main categories:
1. **Direct Attributes** (`vstar_bench_direct_attributes`)
- Questions about direct visual properties such as colors, objects, counts, and characteristics
- Examples: "What is the color of the glove?", "What is the breed of the dog?", "How many people are in the image?"
2. **Relative …
=> [Task] V*-Bench (Visual Star Benchmark)

lmms_eval/api/task.py
Hi, thank you for your awesome project.
I recently wanted to modify the yaml file to use my local dataset since I already have them on my machine.
So I set the 'cache_dir' in the 'dataset_kwargs' and noticed that the lmms-eval is still trying to fetch dataset from huggingface instead of using the local one.
After throughly check, I noticed we can pass in the 'cache_dir' to the huggingface snapshot_download function in the tasks.py if we have 'videos' in dataset_kwargs to avoid force-redownloading.
=> Pass in the 'cache_dir' to use local cache

examples/models/qwen25vl.sh
Following the changes in PR #683, the flash attention parameter interface was updated from `use_flash_attention_2` to `attn_implementation`. This PR updates the shell script to use the correct parameter format.
- Updated `use_flash_attention_2=True` to `attn_implementation=flash_attention_2`
=> [FIX] Fix parameter name in qwen25vl.sh

docs/current_tasks.md, lmms_eval/api/task.py, lmms_eval/tasks/videoevalpro/utils.py, lmms_eval/tasks/videoevalpro/videoevalpro.yaml
Main changes:
1. Add a new task: VideoEval-Pro, a more realistic and robust long video understanding benchmark.
2. Fix small issue when concatenating tar files together.
=> [TASK & FIX] add task VideoEval-Pro and fix tar file concat

lmms_eval/evaluator.py
Fixes #695 where `num_processes=1` with accelerate (running Qwen2.5-VL) leads to error.
This PR updates the synchronization logic in the evaluator to avoid depending on a potentially unset model attribute `lm.accelerator`. It instead uses `Accelerator().wait_for_everyone()` from a new instance, which is safe for single process runs and should behave the same as before for multi-process runs.
- Tested with accelerate on a single-GPU setup. The problem only occurs when `num_processes=1`, so this scenario was reproducible and fixed. Although the fix should behave correctly under both single- and multi-process settings, multi-GPU testing would be recommended.
- `Accelerator().wait_for_everyone()` should work for both backends (`accelerate` and `torchrun`), so the if statement could …
=> [Fix] Fix evaluator crash with accelerate backend when num_processes=1

lmms_eval/tasks/mathvista/mathvista_evals.py
The `API_URL` variable was not used in the MathVista evaluation, which could cause a mismatch between the key and the url in some cases.
=> [Fix] Enable the ignored API_URL in the MathVista evaluation.

README.md, lmms_eval/tasks/videomathqa/README.md, lmms_eval/tasks/videomathqa/cot_postprocess.py, lmms_eval/tasks/videomathqa/cot_step_evaluation.py, lmms_eval/tasks/videomathqa/utils.py, lmms_eval/tasks/videomathqa/videomathqa_mbin.yaml, lmms_eval/tasks/videomathqa/videomathqa_mbin_cot.yaml, lmms_eval/tasks/videomathqa/videomathqa_mbin_cot_w_subtitle.yaml, lmms_eval/tasks/videomathqa/videomathqa_mbin_w_subtitle.yaml, lmms_eval/tasks/videomathqa/videomathqa_mcq.yaml, lmms_eval/tasks/videomathqa/videomathqa_mcq_cot.yaml, lmms_eval/tasks/videomathqa/videomathqa_mcq_cot_w_subtitle.yaml, lmms_eval/tasks/videomathqa/videomathqa_mcq_w_subtitle.yaml
This pull request adds VideoMathQA task to lmms-eval.
VideoMathQA is a benchmark designed to evaluate mathematical reasoning in real-world educational videos. It requires models to interpret and integrate information from three modalities, visuals, audio, and text, across time. The benchmark tackles the needle-in-a-multimodal-haystack problem, where key information is sparse and spread across different modalities and moments in the video.
- 🌐 Project Website: https://mbzuai-oryx.github.io/VideoMathQA
- 🤗 Dataset Access: https://huggingface.co/datasets/MBZUAI/VideoMathQA
- 🏅 Leaderboard (Reasoning): https://hanoonar.github.io/VideoMathQA/#leaderboard-2
- 🏅 Leaderboard (Direct): https://hanoonar.github.io/VideoMathQA/#leaderboard
- 📂 GitHub Repository: …
=> Adds VideoMathQA - Task Designed to Evaluate Mathematical Reasoning in Real-World Educational Videos

examples/models/vllm_qwen2vl.sh, lmms_eval/models/vllm.py
* Better support evaluating vllm outside of example scripts
```bash
python3 -m lmms_eval \
--model vllm \
--model_args model_version=Qwen/Qwen2-VL-7B-Instruct,tensor_parallel_size=4 \
--tasks mme,gsm8k_cot_self_consistency,mmmu_val \
--batch_size 64 \
--log_samples_suffix vllm \
--output_path ./logs \
--limit=64
```
The latest releases of vLLM require that the user specify `VLLM_WORKER_MULTIPROC_METHOD=spawn` for scripts which run vllm in subprocesses
*  Set the `VLLM_WORKER_MULTIPROC_METHOD` environment variable within the vllm model definition directly, rather than at each entrypoint script
* Running `python3 -m lmms_eval --model vllm` now works without having to set the environment variable.
=> [vLLM] centralize VLLM_WORKER_MULTIPROC_METHOD

lmms_eval/tasks/lemonade/utils.py
=> fix linting

lmms_eval/tasks/super_gpqa/super_gpqa.yaml, lmms_eval/tasks/super_gpqa/super_gpqa_multishot.yaml, lmms_eval/tasks/super_gpqa/utils.py
lmms-eval test result:
Qwen__Qwen2.5-7B-Instruct
|  Tasks   |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|----------|------:|------|-----:|--------|---|-----:|---|-----:|
|super_gpqa|      0|none  |     0|accuracy|↑  |0.2924|±  |0.0028|
MegaScience reported score: 28.78
=> add super_gpqa task
